### ISSUE TITLE
Broken Expat Versioning

### ISSUE THREAD

**Issue by ahwm** [Jan-E/svn-windows#3]
```
Downloading https://github.com/libexpat/libexpat/releases/download/R_2_4_2/expat-2.4.1.tar.gz
Error downloading remote file: One or more errors occurred.
Inner Exception: Remote server returned 404: Not Found
```

R_2_4_2 should be 2.4.2, yes?

https://github.com/libexpat/libexpat/releases/download/R_2_4_2/expat-2.4.2.tar.gz

![image](https://user-images.githubusercontent.com/20478373/148859667-9495e77f-40da-4e78-a760-22d085b6763f.png)

**Comment by Jan-E** [comment]
Oops. Thanks.

**Comment by Jan-E** [comment]
https://ci.appveyor.com/project/Jan-E/svn-windows/builds/42152590
The same XFAIL’s (Expected failures) and the same 2 real failures when running the tests, that I am getting in a local build.
